# Hi ha 1 contenidor
# 1. php amb apache (la nostra aplicació web) que la trobaràs a http://localhost:8080
services:
  web:
    image: php:apache
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    build:
      context: ./images
      dockerfile: Dockerfile_php
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html

  db:
    # Tota la informació d'aquesta imatge està https://dockerhub.com/_/mysql
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: passwordDeRootQueNoShaDeFerServirMai
      # És millor no crear la BBDD aquí, ja que no pots control·lar la codificació
      # de caràcters i aleshores donarà problemes amb accents i caràcters especials
      # La BBDD es crearà a l'inici del contenidor amb els script d'inicialització
      # MYSQL_DATABASE: persones
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      LANG: C.UTF-8
    #    El mysql no s'exposa a l'exterior
    #    L'aplicació web hi accedirà per la xarxa interna de docker
    #    ports:
    #      - "3306:3306"

    # La carpeta de mysql ha d'estar al .gitignore per no pujar-la al repositori
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d


# Aquesta imatge és un client web per gestionar el mysql via web
# està disponible a http://localhost:8081
# i les credencials són les del mysql (per que "simplement" es connecta al mysql)
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
